faceEachOther()
say("Otis", "Excellent! Here is your <hint>special power!</hint>", 50, 3000)
wait(300)
setFlag("canPunch", "true")
setFlag("show_mist_orbs", "false")
player.punch("left")
player.punch("right")
player.punch("up")
player.punch("down")
celebrate()
say("Otis", "Now I have granted you a <hint>super punch ability!</hint>", 50, 3500)
saveState()
restoreDirections()
